name: Deploy React App to Strato via SFTP

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Upload to Strato via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "build/*"
          target: "./party_planer"
